### ISSUE TITLE
Suggestion for adding commands in README

### ISSUE THREAD

**Issue by lalit97** [WikipediaLibrary/TWLight#554] opened 2020-10-31 07:23 UTC
Last week I was helping a friend in local setup of the project. After going through the process I thought the commands related to example data generation (`virtualenv_example_data.sh`) and code formatting via black (`docker-compose exec twlight /venv/bin/black -t py37 /app/TWLight`) should be present in the main [README](https://github.com/WikipediaLibrary/TWLight#readmemd).

I thought this way because example data generation command is too common which should be ran at first time setup whereas code formatting command is one which new contributors miss very often and their pull request fails because of this.

**Comment by YashAgrawal9265** [comment] 2020-10-31 07:58
Can I work on this ??

**Comment by lalit97** [comment] 2020-10-31 18:16
Yes but only after any of the core members have the same thoughts as mine i.e. they approve the issue. So just wait for further comments. I will let you know if it gets approved.

**Comment by suecarmol** [comment] 2020-11-19 22:59
Hi @lalit97! Thank you for the suggestion. Can you create a Phabricator task so that the team can take a look at it? You can check how to create a task [here](https://www.mediawiki.org/wiki/Phabricator/Help#Creating_a_task). Be sure to add `The Wikipedia Library` in your tag and we will take a look at it later.

**Comment by lalit97** [comment] 2020-11-22 12:59
Thank you, created one at https://phabricator.wikimedia.org/T268404 :)

**Comment by suecarmol** [comment] 2020-11-23 19:25
Thanks for creating that Phab task! Since the issue is already being discussed there, I'm going to go ahead and close this.

**Closed by suecarmol** 2020-11-23 19:25 UTC

**Comment by lalit97** [comment] 2020-11-24 06:16
Okay, thanks :)
